# Usa un'immagine base di Python
FROM python:3.9-slim

# Installa i pacchetti di sistema necessari per compilare eventuali dipendenze Python
RUN apt-get update && apt-get install -y \
    build-essential \
    libssl-dev \
    libffi-dev \
    python3-dev && \
    rm -rf /var/lib/apt/lists/*

# Crea un ambiente virtuale e aggiungilo al PATH
RUN python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

# Aggiorna pip
RUN pip install --upgrade pip

# Copia il file dei requisiti e installa le dipendenze
COPY requirements.txt /app/requirements.txt
WORKDIR /app
RUN pip install -r requirements.txt

# Copia il resto del codice dell'applicazione nella cartella /app
COPY . /app

# Comando per avviare il bot. Assicurati che "main.py" sia il file giusto.
CMD ["python", "main.py"]
